application: davidshen84
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static

- url: /(.+)/static/(.*)$
  static_files: \1/static/\2
  upload: \1/static/\2$

- url: /blog/admin/
  script: blog.app
  login: admin

- url: /blog/api.*
  script: blog.api
  login: admin

- url: /blog/comment/api.*
  script: blog.api

- url: /blog.*
  script: blog.app

- url: /online-tools/
  static_files: online-tools/index.html
  upload: online-tools/index.html

- url: /online-tools
  static_dir: online-tools
  expiration: 1d

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
