application: davidshen84
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: blog/statics/favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: blog/statics/robots.txt
  upload: robots.txt

- url: /static
  static_dir: blog/statics

- url: /blog/admin/
  script: blog.app
  login: admin

- url: /blog/api.*
  script: blog.app
  login: admin

- url: /blog/comment/api.*
  script: blog.app

- url: /blog.*
  script: blog.app

- url: /mytools/
  script: blog.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
