application: davidshen84
version: beta-0-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico

  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots\.txt

  - url: /blog/resources/.*
    script: blog.resource.app

libraries:
  - name: flask
    version:  "0.12"
  - name: jinja2
    version: "2.6"
  - name: pycrypto
    version: "2.6.1"
  - name: markupsafe
    version: "0.23"
  - name: werkzeug
    version: "0.11.10"
  - name: pytz
    version: "2017.2"
  - name: six
    version: "1.9.0"
  - name: ssl
    version: "2.7.11"

builtins:
  - remote_api: on

env_variables:
  debug: True
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAspxDaMQjotR5gzug7u+F
    fVgLe1tXH/Kt6JHq3A0OnBUXMTjopbnACU3BxOPRV6r27QNoMF7VO5dEbIErBNzd
    TgOPxTtvlggDhoRQxPpr53jVWD3dHMhKQyjgP8wjvS3/44dXlfDEAn0T1DtoLPLq
    8BO8D3lAk4xax57IdgTe7fZ92rfg1ctN7Tbf/Kj6+gmLnqJ+4TbDazD9AoE1C2qn
    rTXHw0Ky/q672+Im2IGHkne72kKcJ9HC5oNIqMN77mHyXH7TrauQwGMYM5ao5n/s
    D3aixmodW8u4OovkmW0XPoUdNs3SZSBJoB66lJhhc0THA+6YthRvQKobgqvm+n1W
    0wIDAQAB
    -----END PUBLIC KEY-----

