runtime: python37

env_variables:
  debug: True
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAspxDaMQjotR5gzug7u+F
    fVgLe1tXH/Kt6JHq3A0OnBUXMTjopbnACU3BxOPRV6r27QNoMF7VO5dEbIErBNzd
    TgOPxTtvlggDhoRQxPpr53jVWD3dHMhKQyjgP8wjvS3/44dXlfDEAn0T1DtoLPLq
    8BO8D3lAk4xax57IdgTe7fZ92rfg1ctN7Tbf/Kj6+gmLnqJ+4TbDazD9AoE1C2qn
    rTXHw0Ky/q672+Im2IGHkne72kKcJ9HC5oNIqMN77mHyXH7TrauQwGMYM5ao5n/s
    D3aixmodW8u4OovkmW0XPoUdNs3SZSBJoB66lJhhc0THA+6YthRvQKobgqvm+n1W
    0wIDAQAB
    -----END PUBLIC KEY-----

