application: davidshen84
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /blog/static
  static_dir: blog/static

- url: /blog/admin
  static_files: blog/admin/admin.html
  upload: blog/admin/admin.html
  login: admin

- url: /blog/admin/
  static_dir: blog/admin
  login: admin

- url: /blog/api.*
  script: blog.myblogapi.app
  login: admin

- url: /blog/comment/api.*
  script: blog.mycommentapi.app

- url: /blog.*
  script: blog.myblog.app

- url: /util/
  static_files: util/main.html
  upload: util/main.html

- url: /util/
  static_dir: util/

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
