application: davidshen84
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /blog/static
  static_dir: static/blog/

- url: /blog/api.*
  script: app.app
  login: admin

- url: /blog/comment/api.*
  script: app.app

- url: /blog/admin/
  script: app.app
  login: admin

- url: /blog/admin/static/
  static_dir: static/admin/
  login: admin

- url: /mytools/
  script: app.app

- url: /mytools/static
  static_dir: static/mytools/

- url: /blog.*
  script: app.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
