application: davidshen84
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /blog/static
  static_dir: app/blog/static

- url: /blog/admin
  static_files: app/blog/admin/admin.html
  upload: app/blog/admin/admin.html
  login: admin

- url: /blog/admin/
  static_dir: app/blog/admin
  login: admin

- url: /blog/api.*
  script: app.blog.myblogapi.app
  login: admin

- url: /blog/comment/api.*
  script: app.blog.mycommentapi.app

- url: /blog.*
  script: app.blog.myblog.app

- url: /util/
  static_files: app/util/main.html
  upload: app/util/main.html

- url: /util/
  static_dir: app/util/

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
